"""Add total_xp to User

Revision ID: 403ec1389c6b
Revises: df8a0853fcfa
Create Date: 2025-12-28 15:34:21.279634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403ec1389c6b'
down_revision: Union[str, Sequence[str], None] = 'df8a0853fcfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'total_xp')
