"""Add streak fields to User

Revision ID: 84fcd8615570
Revises: 8babb544ccab
Create Date: 2025-12-28 10:55:09.511588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fcd8615570'
down_revision: Union[str, Sequence[str], None] = '8babb544ccab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_active_date', sa.DateTime(timezone=True), nullable=True))

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'last_active_date')
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
