"""Add quiz completed to module

Revision ID: de306e3f6e81
Revises: 1308ed04f3cb
Create Date: 2026-01-06 01:47:08.949473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de306e3f6e81'
down_revision: Union[str, Sequence[str], None] = '1308ed04f3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('user_module_progress', sa.Column('quiz_completed', sa.Boolean(), default=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('user_module_progress', 'quiz_completed')
    # ### end Alembic commands ###
