"""Add UserDailyActivity

Revision ID: df8a0853fcfa
Revises: 84fcd8615570
Create Date: 2025-12-28 11:58:04.461684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8a0853fcfa'
down_revision: Union[str, Sequence[str], None] = '84fcd8615570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_daily_activity')
    )
    op.create_index(op.f('ix_user_daily_activity_date'), 'user_daily_activity', ['date'], unique=False)
    op.create_index(op.f('ix_user_daily_activity_id'), 'user_daily_activity', ['id'], unique=False)
    op.create_index(op.f('ix_user_daily_activity_user_id'), 'user_daily_activity', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_user_daily_activity_user_id'), table_name='user_daily_activity')
    op.drop_index(op.f('ix_user_daily_activity_id'), table_name='user_daily_activity')
    op.drop_index(op.f('ix_user_daily_activity_date'), table_name='user_daily_activity')
    op.drop_table('user_daily_activity')
    # ### end Alembic commands ###
