"""Add description and objectives to playlist

Revision ID: fddd286aaee7
Revises: 403ec1389c6b
Create Date: 2025-12-28 16:24:08.507990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fddd286aaee7'
down_revision: Union[str, Sequence[str], None] = '403ec1389c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('playlists', sa.Column('description', sa.String()))
    op.add_column('playlists', sa.Column('objectives', sa.JSON()))
    op.drop_column('playlists', 'content')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('playlists', sa.Column('content', sqlite.JSON(), nullable=True))
    op.drop_column('playlists', 'objectives')
    op.drop_column('playlists', 'description')

    # ### end Alembic commands ###
