name: Deploy FastAPI Lambda

on:
  # pull_request:
  #   branches: ["main"]

  push:
    branches: ["main"]

jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   environment: privacure-dev

  #   steps:
  #     - uses: actions/checkout@v5

  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v7
  #       with:
  #         version: "0.9.15"
  #         python-version: "3.13"
  #         enable-cache: true

  #     - name: Install dependencies
  #       run: uv sync --frozen

  #     - name: Run tests
  #       env:
  #         DATABASE_URL: ${{ secrets.DATABASE_URL }}
  #       run: uv run pytest

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: studyflow

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.15"
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --frozen --no-dev

      - name: Run Alembic migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          USE_MOCK_DATA: ${{ secrets.USE_MOCK_DATA }}
          GOOGLE_OAUTH2_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}
          GOOGLE_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
          SOCIAL_GITHUB_CLIENT_ID: ${{ secrets.SOCIAL_GITHUB_CLIENT_ID }}
          SOCIAL_GITHUB_CLIENT_SECRET: ${{ secrets.SOCIAL_GITHUB_CLIENT_SECRET }}
          APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_PRIVATE_KEY: ${{ secrets.APPLE_PRIVATE_KEY }}
        
        run: |
          uv run alembic upgrade head

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --push .
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_NAME }} \
            --image-uri ${{ steps.build-image.outputs.image }}
          
          aws lambda wait function-updated --function-name ${{ secrets.LAMBDA_NAME }}

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ secrets.ECR_REPO_NAME }} .

      # - name: Tag image
      #   env:
      #     ECR_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}
      #   run: |
      #     docker tag ${{ secrets.ECR_REPO_NAME }}:latest $ECR_URI:latest

      # - name: Push image to ECR
      #   env:
      #     ECR_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}
      #   run: |
      #     docker push $ECR_URI:latest

      # - name: Deploy Lambda
      #   run: |
      #     aws lambda update-function-code \
      #       --function-name ${{ secrets.LAMBDA_NAME }} \
      #       --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
